Theme.create!(name: "Arts & Culture")
Theme.create!(name: "Diasporic")
Theme.create!(name: "Future of Learning")
Theme.create!(name: "Global Community")
Theme.create!(name: "Indigenous Wisdom")
Theme.create!(name: "Nature")
Theme.create!(name: "Other")


Organization.create!(name: "Whynot Theatre", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.", headquarters: "Toronto, Canada", theme_id: 1, website: "http://swb.ca", image: "https://robohash.org/swb-aeroplan-test.png", facebook: "https://www.facebook.com/swbca", instagram: "https://instagram.com", twitter: "https://twitter.com/tweetswb")

Organization.create!(name: "YES", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.", headquarters: "Berkeley", theme_id: 4, website: "http://swb.ca", image: "https://robohash.org/swb-aeroplan-test.png", facebook: "https://www.facebook.com/swbca", instagram: "https://instagram.com", twitter: "https://twitter.com/tweetswb")

Organization.create!(name: "ICTC", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.", headquarters: "Portland", theme_id: 5, website: "http://swb.ca", image: "https://robohash.org/swb-aeroplan-test.png", facebook: "https://www.facebook.com/swbca", instagram: "https://instagram.com", twitter: "https://twitter.com/tweetswb")

Organization.create!(name: "Ecoversities", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.", headquarters: "Lisbon, PT", theme_id: 3, website: "http://swb.ca", image: "https://robohash.org/swb-aeroplan-test.png", facebook: "https://www.facebook.com/swbca", instagram: "https://instagram.com", twitter: "https://twitter.com/tweetswb")

Organization.create!(name: "Enlivened Living", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.", headquarters: "Costa Rica", theme_id: 7, website: "http://swb.ca", image: "https://robohash.org/swb-aeroplan-test.png", facebook: "https://www.facebook.com/swbca", instagram: "https://instagram.com", twitter: "https://twitter.com/tweetswb")

Organization.create!(name: "Shikshantar", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.", headquarters: "Udaipur, India", theme_id: 5, website: "http://swb.ca", image: "https://robohash.org/swb-aeroplan-test.png", facebook: "https://www.facebook.com/swbca", instagram: "https://instagram.com", twitter: "https://twitter.com/tweetswb")

Organization.create!(name: "Collaboration Innovation", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.", headquarters: "Toronto, Canada", theme_id: 1, website: "http://swb.ca", image: "https://robohash.org/swb-aeroplan-test.png", facebook: "https://www.facebook.com/swbca", instagram: "https://instagram.com", twitter: "https://twitter.com/tweetswb")

Organization.create!(name: "Agent of Change/Bstusio", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.", headquarters: "Port of Spain, Trinidad", theme_id: 3, website: "http://swb.ca", image: "https://robohash.org/swb-aeroplan-test.png", facebook: "https://www.facebook.com/swbca", instagram: "https://instagram.com", twitter: "https://twitter.com/tweetswb")

Organization.create!(name: "Project Seres", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.", headquarters: "Guatemala", theme_id: 3, website: "http://swb.ca", image: "https://robohash.org/swb-aeroplan-test.png", facebook: "https://www.facebook.com/swbca", instagram: "https://instagram.com", twitter: "https://twitter.com/tweetswb")

Organization.create!(name: "Foodscapes", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.", headquarters: "Guatemala", theme_id: 6, website: "http://swb.ca", image: "https://robohash.org/swb-aeroplan-test.png", facebook: "https://www.facebook.com/swbca", instagram: "https://instagram.com", twitter: "https://twitter.com/tweetswb")

Organization.create!(name: "Beatbox Without Borders", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.", headquarters: "Oakland", theme_id: 1, website: "http://swb.ca", image: "https://robohash.org/swb-aeroplan-test.png", facebook: "https://www.facebook.com/swbca", instagram: "https://instagram.com", twitter: "https://twitter.com/tweetswb")

Organization.create!(name: "Sketch", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.", headquarters: "Toronto, Canada", theme_id: 1, website: "http://swb.ca", image: "https://robohash.org/swb-aeroplan-test.png", facebook: "https://www.facebook.com/swbca", instagram: "https://instagram.com", twitter: "https://twitter.com/tweetswb")

Organization.create!(name: "Thinking Rock", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.", headquarters: "Thunder Bay", theme_id: 5, website: "http://swb.ca", image: "https://robohash.org/swb-aeroplan-test.png", facebook: "https://www.facebook.com/swbca", instagram: "https://instagram.com", twitter: "https://twitter.com/tweetswb")

Organization.create!(name: "Black Permaculture Network", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.", headquarters: "Oakland", theme_id: 6, website: "http://swb.ca", image: "https://robohash.org/swb-aeroplan-test.png", facebook: "https://www.facebook.com/swbca", instagram: "https://instagram.com", twitter: "https://twitter.com/tweetswb")

Organization.create!(name: "International Permaculture Convergence", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.", headquarters: "London, UK", theme_id: 6, website: "http://swb.ca", image: "https://robohash.org/swb-aeroplan-test.png", facebook: "https://www.facebook.com/swbca", instagram: "https://instagram.com", twitter: "https://twitter.com/tweetswb")

Organization.create!(name: "Whole Person Economy", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.", headquarters: "Berkeley", theme_id: 3, website: "http://swb.ca", image: "https://robohash.org/swb-aeroplan-test.png", facebook: "https://www.facebook.com/swbca", instagram: "https://instagram.com", twitter: "https://twitter.com/tweetswb")

Organization.create!(name: "Groundation Grenada", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.", headquarters: "Grenada", theme_id: 2, website: "http://swb.ca", image: "https://robohash.org/swb-aeroplan-test.png", facebook: "https://www.facebook.com/swbca", instagram: "https://instagram.com", twitter: "https://twitter.com/tweetswb")

Organization.create!(name: "Impact Hub Oakland/Global", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.", headquarters: "Oakland", theme_id: 4, website: "http://swb.ca", image: "https://robohash.org/swb-aeroplan-test.png", facebook: "https://www.facebook.com/swbca", instagram: "https://instagram.com", twitter: "https://twitter.com/tweetswb")

Organization.create!(name: "Gashanty Unity", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.", headquarters: "Toronto, Canada", theme_id: 2, website: "http://swb.ca", image: "https://robohash.org/swb-aeroplan-test.png", facebook: "https://www.facebook.com/swbca", instagram: "https://instagram.com", twitter: "https://twitter.com/tweetswb")

Organization.create!(name: "Shadeism", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.", headquarters: "Toronto, Canada", theme_id: 2, website: "http://swb.ca", image: "https://robohash.org/swb-aeroplan-test.png", facebook: "https://www.facebook.com/swbca", instagram: "https://instagram.com", twitter: "https://twitter.com/tweetswb")

Organization.create!(name: "Wisdom Hackers", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.", headquarters: "New York City & Berlin", theme_id: 3, website: "http://swb.ca", image: "https://robohash.org/swb-aeroplan-test.png", facebook: "https://www.facebook.com/swbca", instagram: "https://instagram.com", twitter: "https://twitter.com/tweetswb")